### ISSUE TITLE
MCEmojiPickerRepresentableController dismisses other VCs

### ISSUE THREAD

**Issue by darvelo** [izyumkin/MCEmojiPicker#16]
`updateUIViewController` may be called multiple times, and I find that this line is dismissing alerts that I've presented:

https://github.com/izyumkin/MCEmojiPicker/blob/220752cfd9bb72d94df7cba52522ddc2e1aec394/Sources/MCEmojiPicker/View/MCEmojiPickerRepresentableController.swift#L125-L126

It's reading the `isPresented` value and dismissing any VC on top, including alerts. When I change the line to:

```swift
        case false:
            if representableController.presentedViewController is MCEmojiPickerViewController {
                representableController.presentedViewController?.dismiss(animated: true)
            }
```

the bug disappears.

**Comment by izyumkin** [comment]
A new version has been published that fixes this problem. Thanks for your contribution!
