### ISSUE TITLE
Weird behaviour in ios 17

### ISSUE THREAD

**Issue by Konstix08** [izyumkin/MCEmojiPicker#18]
I have the emoji picker implemented in an ios 17 app and the emojipicker behaves weird. Sometimes it wont show up, sometimes it is just empty, sometimes it is placed random anywhere on the screen.
I can provide images later. But when you try you can see it yourself.

**Comment by ygee07** [comment]
Same, for me it dismisses the picker immediately upon clicking it without being able to choose an emoji

**Comment by izyumkin** [comment]
I don't have the ability to debug the library for iOS 17 yet. But I think in the near future to install the Xcode beta and check what's new there. 

If possible, describe your problems in more detail, along with screenshots, I will be grateful. And if you have any ideas how to fix these problems, I will be glad to see your pull requests.

**Comment by ygee07** [comment]
Hi @izyumkin, 

It only happens for me when using it with a `Binding` on `ForEach`

```swift
import SwiftUI
import MCEmojiPicker

struct ContentView: View {
   @State var emojis = ["😀", "😁", "😇"]
    
    var body: some View {
        VStack {
            ForEach($emojis, id: \.self) { $emoji in
                EmojiPicker(selection: $emoji)
            }
        }
    }
}

struct EmojiPicker: View {
    @Binding var selection: String
    @State private var isPresented: Bool = false
    
    var body: some View {
        Button(selection) {
            isPresented.toggle()
        }
        .padding()
        .emojiPicker(
            isPresented: $isPresented,
            selectedEmoji: $selection
        )
    }
}
```

Then it behaves like this. 
![2023-07-25 20 29 56](https://github.com/izyumkin/MCEmojiPicker/assets/2621883/3b8349e8-f4d4-47e8-90fa-07c1867fca53)
The picker dismisses immediately without being able to select any other emoji

**Comment by Konstix08** [comment]
i solved my problem bc i adapted my code a bit. But there are a bunch of warnings and i think they are from the framework:
![image](https://github.com/izyumkin/MCEmojiPicker/assets/76095018/27df9a30-9599-45f9-9a12-e4331f4c645e)

**Comment by izyumkin** [comment]
I will try to help you guys soon

<img width="470" alt="Screenshot 2023-07-25 at 20 44 25" src="https://github.com/izyumkin/MCEmojiPicker/assets/50948518/e6361806-dd02-49a8-a233-892a700a8bfa">

**Comment by Konstix08** [comment]
i am on beta 3. I think i update tomorrow

**Comment by ygee07** [comment]
Still seems to be an issue on the latest betas
Xcode 15 Beta 5, iOS 17 Beta 4

**Comment by izyumkin** [comment]
Sorry guys, I have a lot of work on my main job right now. I will try to fix everything by the end of next week🙏

**Comment by izyumkin** [comment]
@ygee07 The bug you had was fixed by @jfpalacios

**Comment by izyumkin** [comment]
@Konstix08 please tell me you still have a lot of warnings? I tried to get a similar result, but it's not working yet

**Comment by ygee07** [comment]
Thank you @izyumkin @jfpalacios
