### ISSUE TITLE
SkinTonePickerView 

### ISSUE THREAD

**Issue by noelle007** [izyumkin/MCEmojiPicker#9]
Hi! Thanks for creating this EmojiPicker! 

I implemented it in my project. It works great, except for the SkinTonePickerView. See attached Screenshot. I checked the view hierarchy, i did see the view was added on top but it was just transparent.  The pickerview is triggered from action in UIContextMenu and presented as a pageSheet. And I have the sourceView as pickerview like `vc.sourceView = vc.view`. Any idea what I missed? 

Thanks a lot!

![IMG_9498](https://user-images.githubusercontent.com/15174280/225247946-ee68fb0f-47e3-4fe2-99d4-8524b2ebe854.jpg)

**Comment by izyumkin** [comment]
Hi! Thank you for using this library, glad to help.

Wow, it's a cool idea to add pageSheet presentation style support. Perhaps I'll add this function.

I managed to achieve the same result as in your screenshot. Fixed the problem and sent a new version of the library to the release, you can test it again. I'm sure it will help you.

The AppsUsing section has also been added to the README file, I would be glad to see your application there!

**Comment by noelle007** [comment]
🙌  It worked!! Thank you so much!
